spring:
  config:
    activate:
      on-profile: dev

mongodb:
  path: mongodb://localhost:27017/test

app:
    openapi:
      swagger-url: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: docker

mongodb:
  path: mongodb://mongodb/docker-db

app:
  openapi:
    swagger-url: http://localhost:8080